site_name: Gluu Docker Edition Docs
site_description: Documentation for the Gluu Server Docker Edition
copyright: Copyright &copy; 2019, Gluu, Inc.
docs_dir: source
repo_name: GluuFederation/docs-de-prod
repo_url: https://github.com/GluuFederation/docs-de-prod
theme:
    name: material
extra:
    version: '3.1.4'
    logo: 'gluu.png'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- pymdownx.superfences
pages:
- 'Introduction': 'index.md'
- 'Technical Documentation': 'technical.md'
- 'Examples': 'example.md'
- 'FAQ': 'faq.md'
