# Project information
site_name: Gluu Docker Edition Docs
site_description: Documentation for Gluu Server Docker Edition
site_favicon: 'favicon.ico'

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: source
#repo_name: GluuFederation/docs-de-prod
repo_url: https://github.com/GluuFederation/docs-de-prod/tree/4.0/docs
#repo_url: https://github.com/GluuFederation/docs-de-prod/
#edit_uri: edit/4.0/docs/source

# Configuration
theme_dir: theme/material
#theme: 
#    name: material
#    palette:
#        primary: 'green'
#        accent: 'green'
#    logo: 'gluu.jpg'
#    favicon: 'favicon.ico'
extra:
    version: '4.0'
    logo: 'gluu.png'
    
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
#- codehilite     
- pymdownx.superfences

# Navigation
#nav:
#- 'Versions':
#    - '4.0': 'https://gluu.org/docs/de/4.0/'
#    - '3.1.6': 'https://gluu.org/docs/de/3.1.6/'
#    - '3.1.5': 'https://gluu.org/docs/de/3.1.5/'
#    - '3.1.4': 'https://gluu.org/docs/de/3.1.4/'
#- ' ': 'https:/gluu.org/docs'
#- ' ': 'https:/gluu.org/docs'
pages:
- 'Introduction': 'index.md'
- 'Technical Reference':
  - 'Build Logic': 'reference/index.md'
  - '3rd-Party Containers': 'reference/third-party.md'
  - 'Config Init': 'reference/config-init.md'
  - 'OpenDJ': 'reference/opendj.md'
  - 'oxAuth': 'reference/oxauth.md'
  - 'oxTrust': 'reference/oxtrust.md'
  - 'oxShibboleth': 'reference/oxshibboleth.md'
  - 'oxPassport': 'reference/oxpassport.md'
  - 'NGINX': 'reference/nginx.md'
  - 'Key Rotation': 'reference/key-rotation.md'
  - 'Upgrade': 'reference/upgrade.md'
- 'Operation Guide':
  - 'Preparing the Server': 'operation/server.md'
  - 'Managing the Vault': 'operation/vault.md'
  - 'Managing Logs': 'operation/logging.md'
  - 'Customizing oxAuth': 'operation/custom-oxauth.md'
  - 'Customizing oxTrust': 'operation/custom-oxtrust.md'
  - 'Custom LDAP Schema': 'operation/custom-schema.md'
  - 'Upgrading': 'operation/upgrade.md'
  - 'oxAuth Key Rotation': 'operation/key-rotation.md'
- 'Deployment Examples':
  - 'Single Host': 'example/singlehost.md'
  - 'Docker Swarm Mode': 'example/swarm-mode.md'
  - 'Minikube': 'example/minikube.md'
  - 'Google Kubernetes Engine': 'example/gke.md'
  # - 'RHEL': 'example/rhel.md'
- 'FAQ': 'faq.md'
