# Project information
site_name: Gluu Docker Edition 3.1.4 Docs
site_description: Documentation for Gluu Server Docker Edition

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-de-prod
repo_url: https://github.com/GluuFederation/docs-de-prod/
edit_uri: edit/3.1.4/docs/source

# Configuration
theme: 
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '3.1.4'
   
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '3.1.4': 'https://gluu.org/docs/de/3.1.4/'
    - '4.0 Beta': 'https://gluu.org/docs/de/4.0/'
    - '3.1.6': 'https://gluu.org/docs/de/3.1.6/'
    - '3.1.5': 'https://gluu.org/docs/de/3.1.5/'
- ' ': 'https:/gluu.org/docs'
- ' ': 'https:/gluu.org/docs'
- 'Introduction': 'index.md'
- 'Technical Documentation': 'technical.md'
- 'Examples': 'example.md'
- 'FAQ': 'faq.md'
